[build]
  command = "CI=false npm install --legacy-peer-deps && npm run build"
  publish = "build"
  functions = "netlify/functions"
  
[functions]
  directory = "netlify/functions"

[context.production.environment]
  CI = "false"